import { Grid } from "@mui/material";
import Head from "next/head";
import React from "react";
import classes from "./Layout.module.css"

import NavButton from "./NavButton";

const Layout = (props) => {
  const videoFile = "/files/videos/bgv.mp4";

  

  return (
    <div>
      <Head>
        <title>東涌出行</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid container spacing={0}>
        {/* <Grid item xs={12}>
          <header className="App-header">
            <div className="display-7 p-2 center">
              <Link href="/">
                <Image
                  src={logoFile}
                  alt="LeaveTungChungSafeNext App Icon"
                  width={75}
                  height={45}
                  sizes="(max-width: 768px) 100vw,
                          (max-width: 1200px) 50vw,
                          33vw"
                />
              </Link>
            </div>
          </header>
        </Grid> */}
        <Grid item xs={12} xl={10}>
          <div style={{ paddingBottom: "100px"}}>{props.children}</div>
        </Grid>
        <Grid item xs={12}>
          <NavButton />
        </Grid>
      </Grid>
      {/* <video autoPlay muted loop id="bgVdo">
        <source src={videoFile} type="video/mp4" />
        Your browser does not support HTML5 video.
      </video> */}
    </div>
  );
};

export default Layout;
